apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: hello-world-backend-config
  namespace: hello-world-ns
spec:
  healthCheck:
    type: HTTP
    requestPath: /
    port: 8080
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
  logging:
    enable: true
    sampleRate: 1.0
