name: GKE Cluster Demo CI

concurrency:
  group: terraform-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches: [main, stage, dev]
  pull_request:
    branches: [main, stage, dev]

permissions:
  contents: read

env:
  GKE_CLUSTER_NAME: ${{ vars.GKE_CLUSTER_NAME }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GKE_REGION: ${{ vars.GKE_REGION }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Authenticate Docker to Google Artifact Registry
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io

  terraform:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

    #   - name: Terraform Init
    #     run: terraform -chdir=terraform init

    #   - name: Terraform Plan
    #     run: terraform -chdir=terraform plan

    #   - name: Terraform Apply
    #     if: github.ref == 'refs/heads/main'
    #     run: terraform -chdir=terraform apply -auto-approve

  docker:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Build Docker image
        run: docker build -t gcr.io/${{ vars.GCP_PROJECT_ID }}/gke-cluster-demo:kube-latest -f kube/Dockerfile kube/

      - name: Push Docker image
        run: docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/gke-cluster-demo:kube-latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

    #   - name: Configure kubectl
    #     run: |
    #       gcloud container clusters get-credentials ${{ vars.GKE_CLUSTER_NAME }} --region ${{ vars.GKE_REGION }} --project ${{ vars.GCP_PROJECT_ID }}
