name: GKE Cluster Demo CI

concurrency:
  group: terraform-${{ github.ref_name }}
  cancel-in-progress: false

on:
  push:
    branches: [main, stage, dev]
  pull_request:
    branches: [main, stage, dev]

permissions:
  contents: read

env:
  GKE_CLUSTER_NAME: ${{ vars.GKE_CLUSTER_NAME }}
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  IMAGE_NAME: hello-world
  REPO_NAME: hello-world-repo
  IMAGE_TAG: 1.2.3
  REGION: us-central1

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Cache gcloud components
        uses: actions/cache@v4
        with:
          path: ~/.config/gcloud
          key: gcloud-${{ runner.os }}-${{ hashFiles('.github/workflows/**') }}
          restore-keys: |
            gcloud-${{ runner.os }}-

      - name: Authenticate Docker to Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            terraform/.terraform
          key: terraform-${{ runner.os }}-${{ hashFiles('terraform/**/*.tf') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Terraform Format
        run: terraform -chdir=terraform fmt -check

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Terraform Plan
        run: terraform -chdir=terraform plan

      - name: Terraform Apply
        # if: github.ref == 'refs/heads/dev'
        run: terraform -chdir=terraform apply -auto-approve

  deploy:
    if: github.event_name != 'delete'
    name: Update Deployment
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GCP_REGION }}
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Update GKE Deployment with New Image
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
        run: |
          kubectl set image deployment/hello-world \
            -n hello-world-ns \
            hello-world="${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

      - name: Verify Kubernetes rollout
        run: |
          if ! kubectl rollout status deployment/hello-world -n hello-world-ns --timeout=300s; then
            echo "Rollout failed, rolling back..."
            kubectl rollout undo deployment/hello-world -n hello-world-ns
            echo "::error::Rollback complete. Deployment did not succeed."
            exit 1
          fi
          echo "Rollout succeeded!"

  docker-build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: terraform-apply
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Authenticate Docker to Google Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Check if image tag exists in Artifact Registry
        id: image-check
        run: |
          IMAGE_PATH="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}"
          IMAGE_TAG="${{ env.IMAGE_TAG }}"
          ERROR_LOG=$(gcloud artifacts docker images describe "${IMAGE_PATH}:${IMAGE_TAG}" --project="${{ env.GCP_PROJECT_ID }}" > /dev/null 2>&1; echo $?)
          if [ "$ERROR_LOG" -eq 0 ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "gcloud error output:" >&2
            gcloud artifacts docker images describe "${IMAGE_PATH}:${IMAGE_TAG}" --project="${{ env.GCP_PROJECT_ID }}"
          fi
      - name: Set up Docker Buildx builder and Build Docker image
        if: steps.image-check.outputs.exists == 'false'
        run: |
          docker buildx create --name mybuilder --driver docker-container --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f kube/Dockerfile kube/ --push
